/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.Inventario;

import app.Inicio.Incio;
import app.bd_conexion.producto_cbd;
import app.datos.categoria;
import app.datos.producto;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.time.format.DateTimeParseException;

public final class AgregarProducto extends javax.swing.JPanel {
    private producto_cbd pcbb = new producto_cbd();
    private Incio inicio;
    public AgregarProducto(Incio inicio) {
        this.inicio = inicio;
        initComponents();
        actualizarCategorias();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tstmedida = new javax.swing.JTextField();
        txtprecio = new javax.swing.JLabel();
        txtprecio1 = new javax.swing.JLabel();
        txtentrada = new javax.swing.JTextField();
        txtprecio2 = new javax.swing.JLabel();
        txtventa = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JComboBox<>();
        txtprecio3 = new javax.swing.JLabel();
        txtvencimiento = new javax.swing.JTextField();
        txtprecio4 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(800, 650));
        setPreferredSize(new java.awt.Dimension(800, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 650));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Producto");

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Codigo");

        jButton11.setBackground(new java.awt.Color(182, 11, 11));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Guardar");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(182, 11, 11));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Descartar");
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Medida");

        tstmedida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tstmedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstmedidaActionPerformed(evt);
            }
        });

        txtprecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprecio.setText("Categoria");

        txtprecio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprecio1.setText("Precio de Entrada");

        txtentrada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentradaActionPerformed(evt);
            }
        });

        txtprecio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprecio2.setText("Precio de Venta ");

        txtventa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtventaActionPerformed(evt);
            }
        });

        txtcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtprecio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprecio3.setText("Fecha de vencimiento");

        txtvencimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvencimientoActionPerformed(evt);
            }
        });

        txtprecio4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprecio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtprecio4.setText("Cantidad");

        txtcantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtprecio4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtventa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtentrada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, 400, Short.MAX_VALUE)
                                    .addComponent(tstmedida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtvencimiento))))
                        .addGap(84, 84, 84)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tstmedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio)
                    .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio1)
                    .addComponent(txtentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio2)
                    .addComponent(txtventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio3)
                    .addComponent(txtvencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprecio4)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed

    }//GEN-LAST:event_txtcodigoActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      // Acción para registrar un producto cuando se presiona el botón correspondiente.
    try {
        validarCampos(); // Validar que todos los campos requeridos están completos.

        // Crear un nuevo objeto 'producto' y establecer sus atributos con los valores de los campos.
        producto p = new producto();
        p.setCodigo(txtcodigo.getText());
        p.setNombre(txtnombre.getText());
        p.setMedida(tstmedida.getText());
        p.setCategoria(txtcategoria.getSelectedItem().toString());
        p.setPrecio_entrada(Double.valueOf(txtentrada.getText()));
        p.setPrecio_salida(Double.valueOf(txtventa.getText()));
        p.setFeche_vencimiento(LocalDate.parse(txtvencimiento.getText()));
        p.setFecha_ingreso(LocalDate.now());
        p.setCantidad(Integer.valueOf(txtcantidad.getText()));

        // Registrar el producto en la base de datos.
        pcbb.RegistrarProducto(p);

        // Mostrar el panel de inventario después de registrar el producto.
        inicio.mostrar(new inventario(inicio));

    } catch (NumberFormatException e) {
        // Manejo de excepción si los campos de entrada, venta y cantidad no contienen valores numéricos válidos.
        JOptionPane.showMessageDialog(inicio, "Los campos de entrada, venta y cantidad deben contener valores numéricos válidos.", "Error de validación", JOptionPane.ERROR_MESSAGE);
    } catch (DateTimeParseException e) {
        // Manejo de excepción si la fecha de vencimiento no tiene un formato válido.
        JOptionPane.showMessageDialog(inicio, "La fecha de vencimiento debe tener un formato válido (YYYY-MM-DD).", "Error de validación", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        // Manejo de excepción si algún campo obligatorio está vacío.
        JOptionPane.showMessageDialog(inicio, e.getMessage(), "Error de validación", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // Manejo de cualquier otra excepción inesperada.
        JOptionPane.showMessageDialog(inicio, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton11ActionPerformed
       
  private void validarCampos() {
    // Método para validar que todos los campos requeridos estén completos.
    if (txtcodigo.getText().isEmpty() || txtnombre.getText().isEmpty() || tstmedida.getText().isEmpty() ||
        txtcategoria.getSelectedItem() == null || txtentrada.getText().isEmpty() || txtventa.getText().isEmpty() ||
        txtvencimiento.getText().isEmpty() || txtcantidad.getText().isEmpty()) {
        throw new IllegalArgumentException("Todos los campos son obligatorios. Por favor, complete la información.");
    }
}
    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
    inicio.mostrar(new inventario(inicio));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void tstmedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstmedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstmedidaActionPerformed

    private void txtentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentradaActionPerformed

    private void txtventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtventaActionPerformed

    private void txtvencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvencimientoActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed
    public void actualizarCategorias() {
    // Método para actualizar el JComboBox 'txtcategoria' con las categorías disponibles.
    try {
        // Obtener la lista de categorías desde la base de datos.
        ArrayList<categoria> listaCategorias = pcbb.obtenerCategorias();

        // Limpiar el contenido actual del JComboBox.
        txtcategoria.removeAllItems();

        // Agregar cada nombre de categoría al JComboBox.
        for (categoria c : listaCategorias) {
            txtcategoria.addItem(c.getCategoria());
        }
    } catch (Exception e) {
        // Manejo de cualquier excepción que ocurra al actualizar las categorías.
        JOptionPane.showMessageDialog(inicio, "Error al actualizar las categorías: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tstmedida;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JComboBox<String> txtcategoria;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtentrada;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JLabel txtprecio;
    private javax.swing.JLabel txtprecio1;
    private javax.swing.JLabel txtprecio2;
    private javax.swing.JLabel txtprecio3;
    private javax.swing.JLabel txtprecio4;
    private javax.swing.JTextField txtvencimiento;
    private javax.swing.JTextField txtventa;
    // End of variables declaration//GEN-END:variables
}
