/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app.Inicio;

import app.Balances.PBalance;
import app.Facturacion.AgregarCliente;
import app.Facturacion.venta;
import app.Inventario.*;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;


public class Incio extends javax.swing.JFrame {

       /**
     * Constructor que inicializa los componentes de la ventana y establece la fecha actual en la interfaz.
     */
    public Incio() {
        initComponents(); // Inicializa los componentes gráficos.
        actualizarFecha(mensaje); // Actualiza la etiqueta con la fecha actual.
        this.setVisible(true); // Hace visible la ventana.
        mostrar(new principal()); // Muestra el panel principal al iniciar la aplicación.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        titulo2 = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        inicio = new javax.swing.JButton();
        Venta = new javax.swing.JButton();
        balance = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        bienvenida = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(1050, 750));
        setMinimumSize(new java.awt.Dimension(1050, 750));

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setMaximumSize(new java.awt.Dimension(1032767, 1032767));
        fondo.setMinimumSize(new java.awt.Dimension(1050, 750));

        menu.setBackground(new java.awt.Color(182, 11, 11));
        menu.setMinimumSize(new java.awt.Dimension(250, 750));
        menu.setPreferredSize(new java.awt.Dimension(250, 750));

        titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Juana Rangel");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        titulo2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Panaderia");

        icono.setForeground(new java.awt.Color(255, 255, 255));
        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setText("icono");
        icono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        inicio.setBackground(new java.awt.Color(182, 11, 11));
        inicio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("Inicio");
        inicio.setBorder(null);
        inicio.setContentAreaFilled(false);
        inicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        Venta.setBackground(new java.awt.Color(182, 11, 11));
        Venta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Venta.setForeground(new java.awt.Color(255, 255, 255));
        Venta.setText("Venta");
        Venta.setBorder(null);
        Venta.setContentAreaFilled(false);
        Venta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaActionPerformed(evt);
            }
        });

        balance.setBackground(new java.awt.Color(182, 11, 11));
        balance.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        balance.setText("Balance");
        balance.setBorder(null);
        balance.setContentAreaFilled(false);
        balance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        inventario.setBackground(new java.awt.Color(182, 11, 11));
        inventario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inventario.setForeground(new java.awt.Color(255, 255, 255));
        inventario.setText("Inventario");
        inventario.setBorder(null);
        inventario.setContentAreaFilled(false);
        inventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(icono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(titulo2)
                    .addContainerGap(672, Short.MAX_VALUE)))
        );

        bienvenida.setBackground(new java.awt.Color(255, 255, 255));
        bienvenida.setMinimumSize(new java.awt.Dimension(800, 100));
        bienvenida.setPreferredSize(new java.awt.Dimension(800, 100));

        mensaje.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("jLabel1");

        javax.swing.GroupLayout bienvenidaLayout = new javax.swing.GroupLayout(bienvenida);
        bienvenida.setLayout(bienvenidaLayout);
        bienvenidaLayout.setHorizontalGroup(
            bienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        bienvenidaLayout.setVerticalGroup(
            bienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setMinimumSize(new java.awt.Dimension(800, 650));
        contenido.setPreferredSize(new java.awt.Dimension(800, 650));
        contenido.setRequestFocusEnabled(false);
        contenido.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
mostrar(new principal());    }//GEN-LAST:event_inicioActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
       mostrar(new inventario(this));
    }//GEN-LAST:event_inventarioActionPerformed

    private void VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaActionPerformed
       mostrar(new venta(this));
    }//GEN-LAST:event_VentaActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        mostrar(new PBalance());
    }//GEN-LAST:event_balanceActionPerformed
    
    /**
     * Método para mostrar un panel en el contenedor principal.
     * @param p El panel que se desea mostrar.
     */
    public void mostrar(JPanel p) {
        // Ajusta el tamaño y posición del panel.
        p.setSize(contenido.getWidth(), contenido.getHeight());
        p.setLocation(0, 0);
        
        // Limpia el contenido actual y agrega el nuevo panel.
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        
        // Refresca el contenedor para asegurar que los cambios sean visibles.
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * Método estático que actualiza una etiqueta JLabel con la fecha actual formateada.
     * @param txtFecha El JLabel donde se mostrará la fecha.
     */
    public static void actualizarFecha(JLabel txtFecha) {
        // Obtiene la fecha y hora actual.
        Calendar calendario = Calendar.getInstance();
        
        // Formatea la fecha en el formato deseado.
        SimpleDateFormat formato = new SimpleDateFormat("EEEE dd 'de' MMMM 'del' yyyy");
        String fechaFormateada = formato.format(calendario.getTime());

        // Actualiza el texto del JLabel con la fecha formateada.
        txtFecha.setText("Bienvenido, hoy es " + fechaFormateada);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Venta;
    private javax.swing.JButton balance;
    private javax.swing.JPanel bienvenida;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel icono;
    private javax.swing.JButton inicio;
    private javax.swing.JButton inventario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
